from pathlib import Path
from typing import Protocol, Sequence


class VideoCatalog(Protocol):
    def discover(self, channel_url: str) -> tuple[dict, list[dict]]: ...


class MediaSource(Protocol):
    def download_audio(self, video_url: str, output_dir: Path) -> Path: ...


class AIProvider(Protocol):
    def transcribe(self, audio_path: Path, language: str = "es", duration_seconds: int | None = None) -> dict: ...
    def embed(self, texts: Sequence[str]) -> dict: ...
    def complete(self, messages: Sequence[dict], max_tokens: int = 512, json_mode: bool = False) -> dict: ...
    def rerank_jev(self, query: str, passages: Sequence[str]) -> dict: ...
